[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/smonsec"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/Echo4058"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/smonsec"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/Echo4058"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/smonsec"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
[[social]]
 name = "youtube"
 type = "social"
 weight = 1
 url = "https://www.youtube.com/channel/UCkUsHyW-NQPQxakh-Uic2XQ"
[[social]]
 name = "facebook"
 weight = 2
 url = "https://web.facebook.com/Glacial0924"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
